---
title: "Lesson Design & Maintenance Guidelines"
editor: visual
---

This page provides guidance for contributors, instructors, and maintainers involved in developing and sustaining Bioconductor training materials. It consolidates expectations, best practices, and processes across all Bioconductor training modules.
Our goal is to ensure that lessons remain high‑quality, accessible, consistent, and easy for the community to maintain.

## Lesson design

- Use RStudio for teaching.
- If possible, finish lessons with a *Next steps* section to highlight
  other relevant Bioconductor lessons. Similarly, in the Summary and
  Setup section, refer to other Bioconductor lessons that cover the
  pre-requisites.
- Whenever relevant, use Bioconductor recommended/maintained classes.
- Package installation: favour `BiocManager::install()` for all
  packages.
- The bioc-intro lesson, which is based on the Ecology lesson, focuses
  on the tidyverse.

## Maintenance

**Maintenance team** Each Bioconductor lesson has at least one
maintainer, and more generally a team of instructors that built and
adviser on the maintenance of the lesson collaboratively. The
maintainer is the person that takes responsibility for merging the PRs
and fixing build issues if/when they happen. The Carpentries
Curriculum Advisory Committee Consultation Rubric provides a template
as to how to address changes to the lessons.

**Contributing and handling minor changes** For minor changes such as
typos or simple rephrasing can be submitted directly through a Github
pull request. The lesson maintainer can assess the PR, ask for
clarifications or amendments and eventually merge the pull request.

**Contributing and handling big changes** For more substantial changes,
we advise to first open an issue to discuss these changes with the
maintainer, the team that created the lesson, and other instructors
that have experience teaching the episode. A pull request for such a
more substantial change (and here, we deliberately don’t define them
explicitly and leave it to the lesson maintainer to assess the
importance), would be discussed in (1) the Github pull request and/or
(2) on the bioconductor-teaching google group and/or, if necessary (3)
during a Bioconductor teaching monthly meeting. For the latter, it
would be recommended that at least 2 to 3 people that were part in the
design of the lesson and/or that have teaching experience would be
present in addition to the lesson maintainer. The PR submitter is also
welcome to join the discussion.

